--- 
abstract: XML::Atom extension for Atom Threading Extensions (RFC 4685)
author: 
  - NAKAGAWA Masaki <masaki@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XML-Atom-Ext-Threading
no_index: 
  directory: 
    - inc
    - t
requires: 
  XML::Atom: 0.28
version: 0.01
